---
name: Release Installer Image
on:
  push:
    paths: ['installer/Dockerfile', 'box64.sh']
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  release:
    name: Release - Docker image
    runs-on: ARM64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          file: installer/Dockerfile
          push: true
          tags: ghcr.io/lambor590/steamcmd_pterodactyl_arm64:installer
          cache-from: type=gha
          cache-to: type=gha,mode=max